const movieQuotes = [
	"Do or do not. There is no 'try' - Yoda",
	"Here's looking at you, kid. - Rick Blaine",
	"May the Force be with you. - Han Solo",
	"You can't handle the truth! - Col. Nathan R. Jessup",
	"I'll be back. - The Terminator",
	"There's no place like home. - Dorothy Gale",
	"You talking to me? - Travis Bickle",
	"You're gonna need a bigger boat. - Chief Martin Brody",
	"Hasta la vista, baby. - The Terminator",
	"I feel the need... the need for speed. - Maverick",
	"The force will be with you, always. - Obi-Wan Kenobi",
	"To infinity and beyond! - Buzz Lightyear",
	"Life is like a box of chocolates. - Forrest Gump",
	"Why so serious? - The Joker",
	"I'm king of the world! - Jack Dawson",
	"There's no crying in baseball. - Jimmy Dugan",
	"E.T. phone home. - E.T.",
	"I coulda been a contender. - Terry Malloy",
	"The stuff that dreams are made of. - Sam Spade",
	"Here's Johnny! - Jack Torrance",
	"I see dead people. - Cole Sear",
	"You have bewitched me, body and soul. - Mr. Darcy",
	"You can't sit with us! - Regina George",
	"I love the smell of napalm in the morning. - Lt. Col. Kilgore",
	"I'm just a girl, standing in front of a boy, asking him to love her. - Anna Scott",
	"We rob banks. - Clyde Barrow",
	"I'm the king of the world! - Jake LaMotta",
	"Fasten your seatbelts. It's going to be a bumpy night. - Margo Channing",
	"Wax on, wax off. - Mr. Miyagi",
	"There's no place like home. There's no place like home. - Dorothy Gale",
	"The road goes ever on and on, down from the door where it began. Now far ahead the road has gone, and I must follow if I can. - Bilbo Baggins",
	"Even the smallest person can change the course of the future. - Galadriel",
	"All we have to decide is what to do with the time that is given us. - Gandalf",
	"Even the smallest person can change the course of history. - Lady Galadriel",
	"I will not say: do not weep; for not all tears are an evil. - Gandalf",
	"It is not despair, for despair is only for those who see the end beyond all doubt. We do not. - Gandalf",
	"The board is set, the pieces are moving. We come to it at last, the great battle of our time. - Gandalf",
	"The treacherous are ever distrustful. - Gandalf",
	"There’s some good in this world, Mr. Frodo… and it’s worth fighting for. - Samwise Gamgee",
	"I would rather share one lifetime with you than face all the ages of this world alone. - Arwen",
	"Fly, you fools! - Gandalf",
];